subtitle: "Stan GSOC 2026"
format: gfm
embed-resources: true
execute: 
  cache: true
  cache-comments: true
  autodep: true
bibliography: references.bib
csl: ieee-with-url.csl

project:
  render:
    - "docs/report.qmd"
